var projects_data = {"projects":[
    {
    	"id": "1621",
    	"title":"YEP Water Northern Uganda", 
    	"summary":"The Dutch Ministry of Foreign Affairs and Netherlands Water Partnership have initiated the Young Expert Programme Water with the objective of providing assurances for the continued availability of international professionalism and expertise in the water sector. In Northern Uganda Paul van Essen from the Netherlands works for Vitens Evides International to work on several water related projects.", 
    	"funded": "100%", 
    	"raised": "€ 40,000", 
    	"focus_area": "", 
    	"who_will_benefit": "", 
    	"goals": "", 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Lira, Uganda, Africa"
    }, 
    {
    	"id": "1630",
    	"title":"One hundred wetlands in Northern Uganda", 
    	"summary":"'One hundred small wetlands' will be constructed & protected to create a natural buffer, trapping the water when there is too much during the rainy season, and releasing it slowly during the dry season.", 
    	"funded": "", 
    	"raised": "", 
    	"focus_area": "", 
    	"who_will_benefit": "", 
    	"goals": ["construction of shallow earth pans or valley dams", "construction of earth dams and weirs", "Community-based water management capacity strengthening", "Strengthening wetlands-supported entrepreneurship and businesses"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Agago, Uganda, Africa"
    },
    {
    	"id": "790",
    	"title":"WaSH program in Rural Bangladesh", 
    	"summary":"Considering the unhealthy and unhygenic environment in rural school and community in southern part of Bangladesh, PSTC will initiate WaSH for schools and communities. lt ensures drinking water and sanitation both in school and community by installing hardware in selected school and areas. In addition, hygiene promotion is done through group meeting/courtyard meeting in school and community.", 
    	"funded": "", 
    	"raised": "", 
    	"focus_area": "", 
    	"who_will_benefit": ["1200 Persons who receive training/capacity building", "1500 institutions with improved sanitation facilities", "18 sanitation systems", "14860 people use improved drinking water", "70 water systems"], 
    	"goals": ["3,600 of School Students get safe water access and ensured their rights", "14,860 of low income community people get safe water access with their ownership", "10 public toilets will be constructed in community", "8 public toilets will be constructed in school", "12 school based rainwater harvesting system will be developed", "Capacity of CBO will be developed on participatory monitoring system on hygiene", "User friendly BCC materials will be developed", "Adolescent girls of the selected school practice menstrual hygiene management"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Botiahgata, Khulna, Bangladesh, Asia"
    },
    {
    	"id": "1587",
    	"title":"Watervoorziening voor school in Kameroen", 
    	"summary":"Government Bilingual Highschool (GBHS) is gelegen in Bamenda in Kameroen. Hier volgen ruim 5000 scholieren middelbaar onderwijs. Omdat de school op een heuvel ligt lukt het het lokale waterbedrijf niet om continu water omhoog te pompen. Zij hebben nu een watertank van 1000 liter waar een paar keer per week water in wordt gepompt. Slechts 1000 liter voor meer dan 5000 leerlingen en het personeel.", 
    	"funded": "100%", 
    	"raised": "€ 4,000", 
    	"focus_area": "", 
    	"who_will_benefit": ["5018 people reached", "2 water systems"], 
    	"goals": ["2 kunststof watertanks van ieder 5 000 Liter"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Bamenda, Cameroon, Africa"
    },
    {
    	"id": "574",
    	"title":"Football for Water in Kisumu", 
    	"summary":"The Football for Water facilities have changed the landscape of the beneficiary rural schools in Kisumu with corresponding high esteem of the schools. This resulted in increased pupil enrolment, promoted good hygiene practices, enhanced retention of pupils especially senior girls who experienced high rate of absenteeism from school during their menses due to lack of proper sanitary facilities.", 
    	"funded": "100%", 
    	"raised": "€ 978,077", 
    	"focus_area": "", 
    	"who_will_benefit": "", 
    	"goals": "", 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Kisumu Municipal, East and West, Kenya, Africa"
    },
    {
    	"id": "657",
    	"title":"Football for Water in Manica", 
    	"summary":"In Manica, Football For Water will cover primary schools in Gondola, Manica and Chimoio district with new WASH infrastructure, WorldCoaches training and football competitions. Football For Water will intervene to boost the quality of life of covered communities and contribute to local development.", 
    	"funded": "100%", 
    	"raised": "€ 969,558", 
    	"focus_area": "", 
    	"who_will_benefit": "", 
    	"goals": "", 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": ""
    },
    {
    	"id": "475",
    	"title":"Health Village: WASH Monitoring Perspective", 
    	"summary":"The project is located in Fakirhat Upazila of Bagerhat District and Barguna Sadr Upazila of Barguna District. The project is about addressing downward accountability and to reduce the 'disconnect' between macro level (policy at National level) and micro level (implementation at union level) to ensure right to water and sanitation -RTWS for women particularly for marginalised.", 
    	"funded": "100%", 
    	"raised": "€ 111,591", 
    	"focus_area": "", 
    	"who_will_benefit": ["18 institutions with improved sanitation facilities", "40000 people use improved sanitation facilities", "40000 people use improved drinking water", "49033 people in communities reached"], 
    	"goals": ["Safe drinking water facilities for 2600 households", "266 women and men are active to raise their voice on WASH", "BDT 200 Million budget is available LGD", "20 local NGOs network members capacited on budget monitoring", "2 out of 3 ministries are well informed on Budget Tracking"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Barguna of Barisal, Bangladesh, Asia"
    },
    {
    	"id": "389",
    	"title":"Rwenzori WASH Alliance Program", 
    	"summary":"This WASH program in Western Uganda will be implemented by the Rwenzori WASH Alliance, consisting of a consortium of HEWASA JESE, PROTOS Uganda and SNV Rwenzori portfolio. It aims to serve at least 400,000 direct beneficiaries and 400,000 indirect beneficiaries within the Rwenzori region over the program period. It will be implemented in the three Districts of Kabarole, Kyenjojo and Kamwenge. Departing from a rights based multi stakeholder approach, this program will work towards improving WASH.", 
    	"funded": "100%", 
    	"raised": "€ 536,128", 
    	"focus_area": "", 
    	"who_will_benefit": ["10920 people affected", "30 years duration", "10920 trainees", "10920 people affected", "30 years duration"], 
    	"goals": ["increased access to water supply", "increased acces to sanitation", "improved hygiene behavior and conditions in target group", "strengthened lobby and advocacy skills of target communities", "improved WASH coordination between district stakeholders"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Fort Portal, Uganda, Africa"
    },
    {
    	"id": "367",
    	"title":"SWASH in Birendranagar, Surkhet", 
    	"summary":"The programme has the main objective to reduce poverty and improve health, environmental and economic conditions in the Mid-Far Western Regions by empowering people and creating an enabling environment, thus achieving increased sustainable access to and use of safe water and sanitation services and improved hygiene practices for women and marginalised groups. Four supporting objectives are envisioned as ways to achieve the main objective.", 
    	"funded": "100%", 
    	"raised": "€ 208,490", 
    	"focus_area": "", 
    	"who_will_benefit": "", 
    	"goals": ["Improved sanitation in 70% of the intervention area", "Access to safe drinking water in 70% of intervention area", "Active WASH stakeholder coordination structures", "Capacity development for partners", "Innovative finance mechanisms in place"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Surkhet, Nepal, Asia"
    },
    {
    	"id": "462",
    	"title":"Northern Region WASH Programme", 
    	"summary":"The Northern Region Water, Sanitation and Hygiene (WASH) Programme is 5-year rolling project using a programmatic approach. It aims to empower communities in the Northern region of Ghana to assert their rights to WASH in order to increase access to WASH facilities and services. It is being implemented by a consortium of 5 NGOs (Simli AiD, Presby Water Project, AFORD Fdn, GYAM and NewEnergy) and mainly supported by SIMAVI under the Dutch WASH Alliance (DWA) framework. It is in its 2nd year of implementation.", 
    	"funded": "100%", 
    	"raised": "€ 604,332", 
    	"focus_area": "", 
    	"who_will_benefit": ["5000 people use improved sanitation facilities", "10 sanitation systems", "20 hygiene facilities", "5000 people use improved drinking water", "20 water systems"], 
    	"goals": ["Foster empowered and assertive communities", "Increase access to improved sustainable WASH services", "Reduce WASH-related diseases in project area", "Train comm'ty structures to sustainably O&M WASH facilities", "Improve health and welbeing of community members"], 
    	"field_partners": "", 
    	"funding_partners": "", 
    	"support_partners": "", 
    	"location": "Tamale, Ghana, Africa"
    },
    
]}